name: disrupton_app
description: Aplicaci칩n de realidad aumentada para exploraci칩n cultural

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  
  # Realidad Aumentada
  ar_flutter_plugin: ^0.7.4
  
  # Estado y navegaci칩n
  provider: ^6.0.5
  go_router: ^10.1.2
  
  # HTTP y API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Almacenamiento local
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # C치mara y permisos
  camera: ^0.10.5+5
  permission_handler: ^10.4.5
  
  # UI y animaciones
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  
  # Utilidades
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    - assets/animations/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
