name: disrupton_app
description: Aplicaci칩n de realidad aumentada para exploraci칩n cultural

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Realidad Aumentada
  ar_flutter_plugin_updated: ^0.0.1
  # Estado y navegaci칩n
  provider: ^6.1.2
  go_router: ^10.1.2
  
  vector_math: ^2.1.4 
  # HTTP y API
  http: ^1.2.1
  dio: ^5.3.2
  http_parser: ^4.0.2
  
  # Almacenamiento local
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  flutter_secure_storage: ^9.2.2
  
  # C치mara y permisos
  camera: ^0.10.6
  permission_handler: ^11.3.1
  
  # UI y animaciones
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  
  # Utilidades
  intl: ^0.19.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    - assets/animations/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
