import '../models/event.dart';

class MockEventService {
  static List<Event> getMockEvents() {
    return [
      Event(
        id: 'event_001',
        title: 'Aprendiendo a Pisar Uva',
        description:
            'Experiencia única de vendimia tradicional donde los participantes aprenderán las técnicas ancestrales de pisado de uva para la elaboración de vinos y piscos artesanales. Un evento cultural que rescata las tradiciones vitivinícolas del Perú.',
        imageUrl: 'assets/images/post_images/aprendiendo_tejidos_andinos.jpeg',
        dateTime: DateTime.parse('2025-03-15T16:00:00Z'),
        location: 'Viñedos de Ica, Perú',
        latitude: -14.0680,
        longitude: -75.7287,
        createdBy: 'admin_user_001',
        createdAt: DateTime.parse('2025-02-10T10:00:00Z'),
        updatedAt: DateTime.parse('2025-02-10T10:00:00Z'),
        isActive: true,
        tags: ['vendimia', 'vino', 'pisco', 'tradición', 'ica'],
        attendeesCount: 45,
        isPastEvent: false,
        timeUntilEvent: '15 días',
      ),
      Event(
        id: 'event_002',
        title: 'Concurso Danza de las Tijeras',
        description:
            'Competencia nacional de la emblemática Danza de las Tijeras, patrimonio cultural inmaterial de la humanidad. Los mejores danzantes de Ayacucho, Huancavelica y Apurímac mostrarán sus habilidades acrobáticas y musicales en un espectáculo único.',
        imageUrl: 'assets/images/post_images/visita_andenes_cotabamba.jpeg',
        dateTime: DateTime.parse('2025-07-28T15:00:00Z'),
        location: 'Plaza de Armas de Ayacucho, Perú',
        latitude: -13.1631,
        longitude: -74.2236,
        createdBy: 'cultural_agent_001',
        createdAt: DateTime.parse('2025-06-05T14:30:00Z'),
        updatedAt: DateTime.parse('2025-06-05T14:30:00Z'),
        isActive: true,
        tags: [
          'danza',
          'tijeras',
          'ayacucho',
          'patrimonio',
          'tradición andina'
        ],
        attendeesCount: 320,
        isPastEvent: false,
        timeUntilEvent: '128 días',
      ),
      Event(
        id: 'event_003',
        title: 'Concurso Nacional de Marinera',
        description:
            'El más prestigioso concurso de marinera del país, donde parejas de todo el Perú compiten por el título de campeones nacionales. La marinera, danza de la costa peruana, muestra elegancia, destreza y tradición en cada paso.',
        imageUrl: 'assets/images/post_images/visita_kuelap.jpeg',
        dateTime: DateTime.parse('2025-01-25T18:00:00Z'),
        location: 'Trujillo, La Libertad, Perú',
        latitude: -8.1116,
        longitude: -79.0288,
        createdBy: 'cultural_agent_002',
        createdAt: DateTime.parse('2024-12-10T09:15:00Z'),
        updatedAt: DateTime.parse('2024-12-10T09:15:00Z'),
        isActive: true,
        tags: ['marinera', 'danza', 'trujillo', 'costa', 'elegancia'],
        attendeesCount: 580,
        isPastEvent: false,
        timeUntilEvent: '55 días',
      ),
      Event(
        id: 'event_004',
        title: 'Festividad Qoyllur Rit\'i',
        description:
            'Peregrinación ancestral al nevado Ausangate, una de las celebraciones religiosas más importantes de los Andes. Miles de peregrinos de comunidades quechuas se reúnen en este santuario a más de 4,600 metros de altura para rendir culto al Señor de Qoyllur Rit\'i.',
        imageUrl: 'assets/images/post_images/visita_lineas_nazca.jpeg',
        dateTime: DateTime.parse('2025-06-16T06:00:00Z'),
        location: 'Santuario de Qoyllur Rit\'i, Cusco, Perú',
        latitude: -13.7500,
        longitude: -71.1667,
        createdBy: 'guide_user_001',
        createdAt: DateTime.parse('2025-04-20T16:45:00Z'),
        updatedAt: DateTime.parse('2025-04-20T16:45:00Z'),
        isActive: true,
        tags: [
          'peregrinación',
          'cusco',
          'andes',
          'religioso',
          'patrimonio',
          'quechua'
        ],
        attendeesCount: 12000,
        isPastEvent: false,
        timeUntilEvent: '107 días',
      ),
      Event(
        id: 'event_005',
        title: 'Inti Raymi',
        description:
            'La Fiesta del Sol, la celebración más importante del Imperio Inca, revive cada año en Cusco. Esta impresionante escenificación en la fortaleza de Sacsayhuamán recrea los rituales incaicos de agradecimiento al dios Sol (Inti) con más de 800 actores.',
        imageUrl: 'assets/images/post_images/visita_machu_picchu.jpeg',
        dateTime: DateTime.parse('2025-06-24T09:00:00Z'),
        location: 'Sacsayhuamán, Cusco, Perú',
        latitude: -13.5089,
        longitude: -71.9828,
        createdBy: 'admin_user_002',
        createdAt: DateTime.parse('2025-04-15T11:20:00Z'),
        updatedAt: DateTime.parse('2025-04-15T11:20:00Z'),
        isActive: true,
        tags: ['inca', 'cusco', 'sol', 'ritual', 'sacsayhuamán', 'patrimonio'],
        attendeesCount: 25000,
        isPastEvent: false,
        timeUntilEvent: '115 días',
      ),
      Event(
        id: 'event_006',
        title: 'Procesión Señor de los Milagros',
        description:
            'La manifestación religiosa más multitudinaria del Perú. Cada octubre, millones de devotos vestidos de morado acompañan la imagen del Cristo Moreno en una procesión que recorre las calles de Lima desde el siglo XVII, siendo la segunda procesión católica más grande del mundo.',
        imageUrl: 'assets/images/post_images/visita_plaza_cusco.jpeg',
        dateTime: DateTime.parse('2025-10-18T10:00:00Z'),
        location: 'Centro Histórico de Lima, Perú',
        latitude: -12.0464,
        longitude: -77.0428,
        createdBy: 'cultural_agent_003',
        createdAt: DateTime.parse('2025-08-25T13:00:00Z'),
        updatedAt: DateTime.parse('2025-08-25T13:00:00Z'),
        isActive: true,
        tags: [
          'religioso',
          'lima',
          'procesión',
          'octubre morado',
          'fe',
          'tradición'
        ],
        attendeesCount: 500000,
        isPastEvent: false,
        timeUntilEvent: '231 días',
      ),
    ];
  }
}
